In [1]:
import pandas

In [2]:
fatalities=pandas.Series(index=['Australia','Albania','Tunisia','France','Monaco'],data=[5.4,15.1,24.4,5.1,"-"])

In [3]:
fatalities

Australia     5.4
Albania      15.1
Tunisia      24.4
France        5.1
Monaco          -
dtype: object

In [4]:
fatalities == "-"

Australia    False
Albania      False
Tunisia      False
France       False
Monaco        True
dtype: bool

In [5]:
fatalities=fatalities.replace("-",0)

In [6]:
fatalities

Australia     5.4
Albania      15.1
Tunisia      24.4
France        5.1
Monaco        0.0
dtype: float64

In [7]:
fatalities2 = fatalities.astype(int)

In [8]:
fatalities

Australia     5.4
Albania      15.1
Tunisia      24.4
France        5.1
Monaco        0.0
dtype: float64

In [9]:
fatalities2

Australia     5
Albania      15
Tunisia      24
France        5
Monaco        0
dtype: int64

In [10]:
fatalies

NameError: name 'fatalies' is not defined

In [ ]:
fatalities.min()

In [ ]:
population=pandas.Series(index=['Australia','France','Tunisia'],data=[24000000,64000000,11375000])

In [ ]:
population*fatalities/100000

In [ ]:
fatalities_count=(population*fatalities/100000)

In [ ]:
fatalities_count.isnull()

In [ ]:
fatalities.max()

In [ ]:
fatalities_count[fatalities_count.notnull()]

In [ ]:
fatalities.idxmax()

In [ ]:
fatalities.idxmin()

In [ ]:
fatalities.mean(),fatalities.median(),fatalities.std()

In [ ]:
fatalities_count.max()

In [ ]:
fatalities_count.idxmax()

In [ ]:
fatalities_count.mean()

In [ ]:
!pip install html5lib
!pip install BeautifulSoup4

In [ ]:
list_of_tables=pandas.read_html('https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)',header=0,index_col=1)

In [ ]:
len(list_of_tables)

In [ ]:
populations=list_of_tables[0]

In [ ]:
populations

In [ ]:
pandas.read_csv('../../SYD_DAT_7/data/sydtrains.csv')

In [11]:
Sydtrains=pandas.read_csv('../../SYD_DAT_7/data/sydtrains.csv',index_col=1,thousands=",")
Sydtrains

,LINE,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
STATION,,,,,,,,,,,,,,,,,,
Central,CBD,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,97110,97110,1,101
Town Hall,CBD,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,89620,89620,2,102
Wynyard,CBD,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,60200,60200,3,103
Parramatta,Western,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,34960,34960,4,905
North Sydney,North Shore,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,28610,28610,5,1402
Redfern,CBD,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,25680,25680,6,108
Chatswood,North Shore,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,22200,22200,7,1407
Bondi Junction,Eastern Suburbs,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,21880,21880,8,203
Strathfield,Inner West,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,20710,20710,9,1110
Circular Quay,CBD,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,20630,20630,10,104
Martin Place,CBD,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,20630,20630,10,107
Hurstville,Illawarra,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,18290,18290,12,310
St Leonards,North Shore,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,17590,17590,13,1405
Blacktown,Western,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,16560,16560,14,911
Burwood,Inner West,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,14990,14990,15,1109
Kings Cross,Eastern Suburbs,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,12870,12870,16,201
Hornsby,North Shore,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,12250,12250,17,1417
Ashfield,Inner West,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,11200,11200,18,1107
Kogarah,Illawarra,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,11100,11100,19,307
Lidcombe,South,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,10910,10910,20,702
Auburn,Western,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,10890,10890,21,901
Museum,CBD,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,10860,10860,22,106
Epping,Northern via Strathfield,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,10570,10570,23,1208
Macquarie University,Northern via Macquarie Park,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,10090,10090,24,1303
St James,CBD,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,9850,9850,25,105
Rockdale,Illawarra,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,9640,9640,26,306
Cabramatta,South,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,8730,8730,27,708
Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,8630,8630,28,612
Liverpool,South,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,8350,8350,29,710
Sutherland,Illawarra,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,8320,8320,30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Newcastle,Newcastle,2004,19/06/2003,No,50,20,260,320,720,850,430,200,70,140,1530,1530,123,1917
Waratah,Hunter,2004,16/10/2001,No,0,0,100,100,150,150,120,120,40,30,410,410,193,2001
Warabrook (University),Hunter,2004,16/10/2001,No,10,10,20,250,120,200,300,70,90,20,540,540,185,2002
Sandgate,Hunter,2004,16/10/2001,No,0,0,10,10,10,10,20,20,0,0,40,40,267,2003
Hexham,Hunter,2004,16/10/2001,No,0,0,10,20,10,20,20,10,10,0,50,50,258,2004
Tarro,Hunter,2004,16/10/2001,No,0,0,20,0,0,10,0,10,0,0,20,20,278,2005
Beresfield,Hunter,2004,16/10/2001,No,0,0,180,80,140,110,70,180,10,40,400,400,195,2006
Thornton,Hunter,2004,16/10/2001,No,0,0,150,20,60,80,50,150,10,20,270,270,211,2007
Metford,Hunter,2004,16/10/2001,No,0,0,100,20,50,50,20,90,10,10,180,180,231,2008
Victoria Street,Hunter,2004,16/10/2001,No,0,0,190,50,120,120,70,180,20,50,400,400,195,2009
East Maitland,Hunter,2004,16/10/2001,No,0,0,20,50,50,40,50,20,0,10,120,120,240,2010
High Street,Hunter,2004,16/10/2001,No,0,0,30,40,40,40,30,40,10,0,110,110,248,2011
Maitland,Hunter,2004,16/10/2001,No,0,10,190,100,180,210,150,180,20,40,540,540,185,2012
Telarah,Hunter,2004,24/08/2004,Yes,0,0,110,30,60,60,50,120,20,30,240,240,218,2013
Mindaribba,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2014
Paterson,Hunter,2004,24/08/2004,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
Martins Creek,Hunter,2004,24/08/2004,Yes,0,0,10,0,0,0,0,0,0,0,10,10,283,2016
Hilldale,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2017
Wallarobba,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2018
Wirragulla,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2019
Dungog,Hunter,2004,24/08/2004,Yes,0,0,20,0,10,20,10,20,0,10,40,40,267,2020
Lochinvar,Hunter,2004,24/08/2004,Yes,0,0,10,0,0,0,0,0,0,0,10,10,283,2021
Allandale,Hunter,2004,16/10/2001,No,0,0,0,0,0,0,0,0,0,0,0,0,295,2022
Greta,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2023
Branxton,Hunter,2004,24/08/2004,Yes,0,0,20,0,0,0,0,10,0,10,20,20,278,2024
Belford,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2025
Singleton,Hunter,2004,24/08/2004,Yes,0,0,30,10,0,0,10,30,10,10,50,50,258,2026
Muswellbrook,Hunter,2004,24/08/2004,Yes,0,0,10,0,30,10,0,40,10,20,50,50,258,2027
Aberdeen,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,10,10,10,283,2028
Scone,Hunter,2004,24/08/2004,Yes,10,0,0,0,0,0,0,10,0,0,10,10,283,2029

In [12]:
Sydtrains

,LINE,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
STATION,,,,,,,,,,,,,,,,,,
Central,CBD,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,97110,97110,1,101
Town Hall,CBD,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,89620,89620,2,102
Wynyard,CBD,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,60200,60200,3,103
Parramatta,Western,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,34960,34960,4,905
North Sydney,North Shore,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,28610,28610,5,1402
Redfern,CBD,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,25680,25680,6,108
Chatswood,North Shore,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,22200,22200,7,1407
Bondi Junction,Eastern Suburbs,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,21880,21880,8,203
Strathfield,Inner West,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,20710,20710,9,1110
Circular Quay,CBD,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,20630,20630,10,104
Martin Place,CBD,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,20630,20630,10,107
Hurstville,Illawarra,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,18290,18290,12,310
St Leonards,North Shore,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,17590,17590,13,1405
Blacktown,Western,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,16560,16560,14,911
Burwood,Inner West,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,14990,14990,15,1109
Kings Cross,Eastern Suburbs,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,12870,12870,16,201
Hornsby,North Shore,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,12250,12250,17,1417
Ashfield,Inner West,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,11200,11200,18,1107
Kogarah,Illawarra,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,11100,11100,19,307
Lidcombe,South,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,10910,10910,20,702
Auburn,Western,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,10890,10890,21,901
Museum,CBD,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,10860,10860,22,106
Epping,Northern via Strathfield,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,10570,10570,23,1208
Macquarie University,Northern via Macquarie Park,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,10090,10090,24,1303
St James,CBD,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,9850,9850,25,105
Rockdale,Illawarra,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,9640,9640,26,306
Cabramatta,South,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,8730,8730,27,708
Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,8630,8630,28,612
Liverpool,South,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,8350,8350,29,710
Sutherland,Illawarra,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,8320,8320,30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Newcastle,Newcastle,2004,19/06/2003,No,50,20,260,320,720,850,430,200,70,140,1530,1530,123,1917
Waratah,Hunter,2004,16/10/2001,No,0,0,100,100,150,150,120,120,40,30,410,410,193,2001
Warabrook (University),Hunter,2004,16/10/2001,No,10,10,20,250,120,200,300,70,90,20,540,540,185,2002
Sandgate,Hunter,2004,16/10/2001,No,0,0,10,10,10,10,20,20,0,0,40,40,267,2003
Hexham,Hunter,2004,16/10/2001,No,0,0,10,20,10,20,20,10,10,0,50,50,258,2004
Tarro,Hunter,2004,16/10/2001,No,0,0,20,0,0,10,0,10,0,0,20,20,278,2005
Beresfield,Hunter,2004,16/10/2001,No,0,0,180,80,140,110,70,180,10,40,400,400,195,2006
Thornton,Hunter,2004,16/10/2001,No,0,0,150,20,60,80,50,150,10,20,270,270,211,2007
Metford,Hunter,2004,16/10/2001,No,0,0,100,20,50,50,20,90,10,10,180,180,231,2008
Victoria Street,Hunter,2004,16/10/2001,No,0,0,190,50,120,120,70,180,20,50,400,400,195,2009
East Maitland,Hunter,2004,16/10/2001,No,0,0,20,50,50,40,50,20,0,10,120,120,240,2010
High Street,Hunter,2004,16/10/2001,No,0,0,30,40,40,40,30,40,10,0,110,110,248,2011
Maitland,Hunter,2004,16/10/2001,No,0,10,190,100,180,210,150,180,20,40,540,540,185,2012
Telarah,Hunter,2004,24/08/2004,Yes,0,0,110,30,60,60,50,120,20,30,240,240,218,2013
Mindaribba,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2014
Paterson,Hunter,2004,24/08/2004,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
Martins Creek,Hunter,2004,24/08/2004,Yes,0,0,10,0,0,0,0,0,0,0,10,10,283,2016
Hilldale,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2017
Wallarobba,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2018
Wirragulla,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2019
Dungog,Hunter,2004,24/08/2004,Yes,0,0,20,0,10,20,10,20,0,10,40,40,267,2020
Lochinvar,Hunter,2004,24/08/2004,Yes,0,0,10,0,0,0,0,0,0,0,10,10,283,2021
Allandale,Hunter,2004,16/10/2001,No,0,0,0,0,0,0,0,0,0,0,0,0,295,2022
Greta,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2023
Branxton,Hunter,2004,24/08/2004,Yes,0,0,20,0,0,0,0,10,0,10,20,20,278,2024
Belford,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2025
Singleton,Hunter,2004,24/08/2004,Yes,0,0,30,10,0,0,10,30,10,10,50,50,258,2026
Muswellbrook,Hunter,2004,24/08/2004,Yes,0,0,10,0,30,10,0,40,10,20,50,50,258,2027
Aberdeen,Hunter,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,10,10,10,283,2028
Scone,Hunter,2004,24/08/2004,Yes,10,0,0,0,0,0,0,10,0,0,10,10,283,2029

In [17]:
Train2014=Sydtrains[Sydtrains.YEAR == 2014]
Train2014

,LINE,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
STATION,,,,,,,,,,,,,,,,,,
Central,CBD,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,97110,97110,1,101
Town Hall,CBD,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,89620,89620,2,102
Wynyard,CBD,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,60200,60200,3,103
Parramatta,Western,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,34960,34960,4,905
North Sydney,North Shore,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,28610,28610,5,1402
Redfern,CBD,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,25680,25680,6,108
Chatswood,North Shore,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,22200,22200,7,1407
Bondi Junction,Eastern Suburbs,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,21880,21880,8,203
Strathfield,Inner West,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,20710,20710,9,1110
Circular Quay,CBD,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,20630,20630,10,104
Martin Place,CBD,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,20630,20630,10,107
Hurstville,Illawarra,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,18290,18290,12,310
St Leonards,North Shore,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,17590,17590,13,1405
Blacktown,Western,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,16560,16560,14,911
Burwood,Inner West,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,14990,14990,15,1109
Kings Cross,Eastern Suburbs,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,12870,12870,16,201
Hornsby,North Shore,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,12250,12250,17,1417
Ashfield,Inner West,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,11200,11200,18,1107
Kogarah,Illawarra,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,11100,11100,19,307
Lidcombe,South,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,10910,10910,20,702
Auburn,Western,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,10890,10890,21,901
Museum,CBD,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,10860,10860,22,106
Epping,Northern via Strathfield,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,10570,10570,23,1208
Macquarie University,Northern via Macquarie Park,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,10090,10090,24,1303
St James,CBD,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,9850,9850,25,105
Rockdale,Illawarra,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,9640,9640,26,306
Cabramatta,South,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,8730,8730,27,708
Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,8630,8630,28,612
Liverpool,South,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,8350,8350,29,710
Sutherland,Illawarra,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,8320,8320,30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Menangle Park,Southern Highlands,2014,19/06/2014,Yes,0,0,10,0,10,10,0,10,0,0,20,20,277,1601
Port Kembla North,South Coast,2014,18/09/2014,Yes,0,0,0,10,10,0,10,10,0,0,20,20,277,1521
Scone,Hunter,2014,3/06/2009,No,10,0,0,0,0,0,0,10,10,10,20,20,277,2029
Tarro,Hunter,2014,3/06/2009,No,0,0,10,0,10,0,0,10,0,0,20,20,277,2005
Aberdeen,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2028
Bombo,South Coast,2014,18/09/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1530
Branxton,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2024
Burradoo,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1610
Coalcliff,South Coast,2014,9/08/2012,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1504
Dunmore (Shellharbour),South Coast,2014,18/06/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1528
Exeter,Southern Highlands,2014,25/05/2010,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1612
Greta,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,10,0,0,10,10,283,2023
Linden,Blue Mountains,2014,19/08/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1708
Marulan,Southern Highlands,2014,17/06/2014,Yes,0,0,0,0,0,0,0,0,10,10,10,10,283,1617
Menangle,Southern Highlands,2014,17/06/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1602
Paterson,Hunter,2014,3/06/2009,No,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
Scarborough,South Coast,2014,22/08/2013,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1505
Tallong,Southern Highlands,2014,25/05/2010,No,0,0,10,0,0,0,0,0,0,10,10,10,283,1616
Wondabyne,Central Coast,2014,21/11/2012,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1803
Bell,Blue Mountains,2014,0,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1719
Hilldale,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2017
Kembla Grange Racecourse,South Coast,2014,15/02/1996,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1524
Lochinvar,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2021
Lysaghts,South Coast,2014,12/11/2013,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1519
Mindaribba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2014
Penrose,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1614
Wallarobba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2018
Wingello,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1615
Wirragulla,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2019
Zig Zag,Blue Mountains,2014,9/10/2014,Yes,0,0,0,0,0,0,0,0,0,0,0,0,298,1720

In [19]:
Train2014.IN_24_HOURS.idxmax()

'Central'

In [20]:
Train2014[Train2014.IN_24_HOURS == 0]

,LINE,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
STATION,,,,,,,,,,,,,,,,,,
Bell,Blue Mountains,2014,0,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1719
Hilldale,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2017
Kembla Grange Racecourse,South Coast,2014,15/02/1996,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1524
Lochinvar,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2021
Lysaghts,South Coast,2014,12/11/2013,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1519
Mindaribba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2014
Penrose,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1614
Wallarobba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2018
Wingello,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1615
Wirragulla,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2019
Zig Zag,Blue Mountains,2014,9/10/2014,Yes,0,0,0,0,0,0,0,0,0,0,0,0,298,1720

In [35]:
Train2014 [['IN_0200_0600','OUT_0200_0600']].head5

AttributeError: 'DataFrame' object has no attribute 'head5'